db:
   image: mysql:5.6
   environment:
      - MYSQL_ROOT_PASSWORD
      - MYSQL_USER=sonar
      - MYSQL_PASSWORD=sonar
      - MYSQL_DATABASE=sonar
   volumes:
      - /var/lib/mysql
   ports:
      - "13306:3306"
web:
   build: .
   ports:
      - "9000:9000"
   links:
      - db